from scipy import special
import numpy as np
import matplotlib.pyplot as plt
import math
plt.figure(1)
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

#plt.plot(x, [max(0,i) for i in x])

#plt.plot(x, x/(1+np.exp(-x)))
#plt.plot(x, 5*x/(5+np.exp(-x)))
y = x/(1 + np.exp(-x))
plt.plot(x, y+y*(1-y)/x)
#plt.plot(x,np.log(np.exp(x)+1)+0.2*x)
#plt.plot(x, 1/(1+np.exp(-x)))
#plt.plot(x,np.tanh(x))
#plt.plot(x,0.5*np.log(2+np.exp(2*x)+np.exp(-2*x)))
#plt.plot(x, 5*x/(5+np.exp(-x)))
#plt.plot(x,5/(5+np.exp(-x)) + 5*x*np.exp(-x)/((5+np.exp(-x))*(5+np.exp(-x))))
#plt.plot(x, 10*x/(10+np.exp(-x)))
#plt.plot(x,10/(10+np.exp(-x)) + 10*x*np.exp(-x)/((10+np.exp(-x))*(10+np.exp(-x))))
#plt.plot(x, 30*x/(30+np.exp(-x)))
#plt.plot(x,30/(30+np.exp(-x)) + 30*x*np.exp(-x)/((30+np.exp(-x))*(30+np.exp(-x))))
#plt.plot(x, x/(1+np.exp(-x)))
#plt.plot(x, x/(1+np.exp(-0.3*x)))
#plt.plot(x, 20*x/(20+np.exp(-x)))
#plt.plot(x, x/(1+np.exp(-x)))
plt.plot(x, x)
#plt.plot(x, special.erfc(-x/math.sqrt(2.0))/2.0)
#plt.plot(x, special.erfc(-x)/2.0)
#plt.plot(x, 1/(np.pi*(1+x*x)))
#plt.plot(x, x*1/2.0 + x*np.arctan(x)*1/np.pi)
#plt.plot(x,np.arctan(x)/np.pi)
#plt.plot(x, np.exp(-0.5*x*x)/np.sqrt(2*np.pi))
#plt.plot(x, x*0.5*(1+special.erf(x/np.sqrt(2))))
#plt.plot(x, np.arctan(x))
#plt.plot(x, [i if i > 0 else np.exp(i)-1 for i in x])
plt.plot(x, x/(1+np.exp(-x)))
#plt.plot(x, x+(np.exp(x)-1)/np.pi)
#plt.plot(x, np.zeros(x.shape))
#plt.plot(x, 0.5*x*(1+np.tanh(math.sqrt(2/math.pi)*(x+0.044715*x*x*x))))
#plt.plot(x, 1/(1+np.exp(-x)))
#plt.plot(x, [0 for i in x], 'k')
#plt.plot([0 for i in y], y, 'k')
plt.legend(['relu', 'gelu', 'silu','test','x','y'])
plt.show()
